# Generated by Django 3.1.3 on 2022-05-18 07:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('contents', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('request_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.store')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
