# Generated by Django 3.1.3 on 2022-05-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='contents',
        ),
    ]
