# Generated by Django 3.1.3 on 2022-05-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20220520_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='n_file',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='notice_cate',
        ),
        migrations.AddField(
            model_name='notice_cate',
            name='notice_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.notice'),
        ),
        migrations.AddField(
            model_name='notice_file',
            name='n_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.notice'),
        ),
    ]
