# Generated by Django 3.1.3 on 2022-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20220530_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='visdis',
            field=models.CharField(default='1', max_length=300),
        ),
    ]
