# Generated by Django 3.1.3 on 2022-05-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20220530_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_title',
            field=models.CharField(max_length=300),
        ),
    ]
