# Generated by Django 3.1.3 on 2022-06-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_store_agency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='agency_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
