# Generated by Django 3.1.3 on 2022-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_store_agency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=300)),
                ('files', models.FileField(null=True, upload_to='documnet')),
                ('upload_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
