# Generated by Django 3.1.3 on 2022-06-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_cal_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
