# Generated by Django 3.1.3 on 2022-06-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_store_cal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cal_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
