# Generated by Django 3.1.3 on 2022-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_store_cal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cal_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
