# Generated by Django 3.1.3 on 2022-06-15 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
        migrations.AddField(
            model_name='images',
            name='image_tabe_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.image_table'),
            preserve_default=False,
        ),
    ]
