# Generated by Django 3.1.3 on 2022-06-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_remove_images_image_tabe_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_table',
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
