# Generated by Django 3.1.3 on 2022-06-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_auto_20220615_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='uploadedFile',
            field=models.FileField(upload_to='drfProject/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
