# Generated by Django 3.1.3 on 2022-06-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_auto_20220615_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='uploadedFile',
            field=models.FileField(upload_to='drfProject/'),
        ),
    ]
