# Generated by Django 3.1.3 on 2022-06-20 05:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='contents',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
