# Generated by Django 3.1.3 on 2022-06-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_auto_20220620_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='Notice_cate',
            field=models.CharField(default='', max_length=300),
        ),
    ]
