# Generated by Django 3.1.3 on 2022-06-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_notice_notice_cate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice_cate',
        ),
    ]
