# Generated by Django 3.1.3 on 2022-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_delete_notice_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_file',
            name='Notice_file',
            field=models.FileField(upload_to='Notice_project/'),
        ),
    ]
