# Generated by Django 3.1.3 on 2022-06-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_auto_20220621_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='important',
            field=models.BooleanField(default=True),
        ),
    ]
