# Generated by Django 3.1.3 on 2022-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_notice_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certi_num',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
