# Generated by Django 3.1.3 on 2022-09-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_user_certi_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='needed_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
